---
- name: optimization -- short circuit slow call to apt_key
  sudo: yes
  command: apt-key list
  register: apt_key_list
  changed_when: False

- name: add wtanaka ppa key to apt-key
  apt_key: file=/root/wtanaka_ppa.gpg
  sudo: yes
  when: "'29610B46' not in apt_key_list.stdout"

- name: wtanaka sources.list
  template: >
    src=wtanaka-com.list.j2
    dest=/etc/apt/sources.list.d/wtanaka-com.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes

- name: Install php52-fpm
  apt: name=php52-fpm
  sudo: yes
