---
- include: compat.yml
- include: get_key.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: fpm config file
  sudo: True
  template: >
    src=php-fpm.conf.j2
    dest=/etc/php52/php-fpm.conf

- name: config file
  sudo: True
  file:
    path: /etc/php5/fpm/pool.d
    state: directory

- name: config file
  sudo: True
  template: >
    src=www.conf.j2
    dest=/etc/php5/fpm/pool.d/www.conf

- name: ensure php52-fpm is running (and enable it at boot)
  sudo: yes
  service: name=php52-fpm state=started enabled=yes
  changed_when: False
